[2024-11-19T07:54:28.380+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_reddit_pipeline.s3_upload manual__2024-11-19T07:54:24.059916+00:00 [queued]>
[2024-11-19T07:54:28.388+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_reddit_pipeline.s3_upload manual__2024-11-19T07:54:24.059916+00:00 [queued]>
[2024-11-19T07:54:28.388+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2024-11-19T07:54:28.399+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): s3_upload> on 2024-11-19 07:54:24.059916+00:00
[2024-11-19T07:54:28.403+0000] {standard_task_runner.py:57} INFO - Started process 101 to run task
[2024-11-19T07:54:28.407+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'etl_reddit_pipeline', 's3_upload', 'manual__2024-11-19T07:54:24.059916+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/reddit_dag.py', '--cfg-path', '/tmp/tmpsx0cr6m7']
[2024-11-19T07:54:28.410+0000] {standard_task_runner.py:85} INFO - Job 13: Subtask s3_upload
[2024-11-19T07:54:28.452+0000] {task_command.py:416} INFO - Running <TaskInstance: etl_reddit_pipeline.s3_upload manual__2024-11-19T07:54:24.059916+00:00 [running]> on host 71ecfcab0f8c
[2024-11-19T07:54:28.522+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Bao Nguyen' AIRFLOW_CTX_DAG_ID='etl_reddit_pipeline' AIRFLOW_CTX_TASK_ID='s3_upload' AIRFLOW_CTX_EXECUTION_DATE='2024-11-19T07:54:24.059916+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-19T07:54:24.059916+00:00'
[2024-11-19T07:54:28.546+0000] {logging_mixin.py:151} INFO - Provided region_name '{AWS_REGION}' doesn't match a supported format.
[2024-11-19T07:54:28.549+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/pipelines/aws_s3_pipeline.py", line 9, in upload_s3_pipeline
    upload_to_s3(s3, file_path, AWS_BUCKET_NAME, file_path.split('/')[-1])
  File "/opt/airflow/etls/aws_etl.py", line 25, in upload_to_s3
    s3.put(file_path, bucket+'/raw/'+s3_file_name)
  File "/home/airflow/.local/lib/python3.9/site-packages/fsspec/asyn.py", line 118, in wrapper
    return sync(self.loop, func, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/fsspec/asyn.py", line 103, in sync
    raise return_result
  File "/home/airflow/.local/lib/python3.9/site-packages/fsspec/asyn.py", line 56, in _runner
    result[0] = await coro
  File "/home/airflow/.local/lib/python3.9/site-packages/fsspec/asyn.py", line 536, in _put
    trailing_sep(rpath) or await self._isdir(rpath)
  File "/home/airflow/.local/lib/python3.9/site-packages/s3fs/core.py", line 1411, in _isdir
    return bool(await self._lsdir(path))
  File "/home/airflow/.local/lib/python3.9/site-packages/s3fs/core.py", line 706, in _lsdir
    async for c in self._iterdir(
  File "/home/airflow/.local/lib/python3.9/site-packages/s3fs/core.py", line 737, in _iterdir
    await self.set_session()
  File "/home/airflow/.local/lib/python3.9/site-packages/s3fs/core.py", line 527, in set_session
    self._s3 = await s3creator.__aenter__()
  File "/home/airflow/.local/lib/python3.9/site-packages/aiobotocore/session.py", line 27, in __aenter__
    self._client = await self._coro
  File "/home/airflow/.local/lib/python3.9/site-packages/aiobotocore/session.py", line 140, in _create_client
    region_name = self._resolve_region_name(region_name, config)
  File "/home/airflow/.local/lib/python3.9/site-packages/botocore/session.py", line 1023, in _resolve_region_name
    validate_region_name(region_name)
  File "/home/airflow/.local/lib/python3.9/site-packages/botocore/utils.py", line 1309, in validate_region_name
    raise InvalidRegionError(region_name=region_name)
botocore.exceptions.InvalidRegionError: Provided region_name '{AWS_REGION}' doesn't match a supported format.
[2024-11-19T07:54:28.561+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=etl_reddit_pipeline, task_id=s3_upload, execution_date=20241119T075424, start_date=20241119T075428, end_date=20241119T075428
[2024-11-19T07:54:28.571+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 13 for task s3_upload (Provided region_name '{AWS_REGION}' doesn't match a supported format.; 101)
[2024-11-19T07:54:28.587+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-11-19T07:54:28.602+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
